title: Метод научного тыка
description: Заметки на память и вообще...
author: Олег Фомичёв

disclaimer: Да и хрен с ним!

excerpt_separator: <!--more-->
permalink: pretty

url: https://fomich0ff.github.io

disqus:
    shortname: fomich0ff-github-io
    api_publik_key: NO5WyhfWJ9szGoE6Ny2OpKqGGGjxEhWtNaq84Cx7fiYtf6nfwOuGYv2z3vX1PkuL
    url: https://disqus.com/api/3.0/forums/listThreads.json?forum=
