title: Метод научного тыка
description: Заметки на память и вообще...
disclaimer: Ура!

highlighter: none

future: true

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: Олег Фомичёв
            email: fomich0ff.github.io@gmail.com
            comments: true
            layout: post
            read-more: Дальше...

excerpt_separator: <!--more-->
permalink: pretty

url: https://fomich0ff.github.io

disqus:
    enabled: true
    shortname: fomich0ff-github-io
    api-publik-key: NO5WyhfWJ9szGoE6Ny2OpKqGGGjxEhWtNaq84Cx7fiYtf6nfwOuGYv2z3vX1PkuL
    url: https://disqus.com/api/3.0/forums/listThreads.json?forum=

google:
    google-analytics:
        enabled: true
        code: UA-38646029-3

page-navigation:
    enabled: true
    show-pointers: true
    show-labels: false
    show-page-titles: true
    previous:
        label: Назад к
        pointer: |
            &laquo;
    next:
        label: Вперед к
        pointer: |
            &raquo;
