title: Метод научного тыка
description: Заметки на память и вообще...
disclaimer: |
    Всё, что находится в этом блоге является результатом различных экспериментов и умозаключений автора, а также компиляцией информации из различных источников. Вся информация представлена как есть и не является истиной в последней инстанции. Более того часть ее могла устареть (и наверняка давно это сделала). И помните: с двенадцатым ударом... ой, не про то... вы используете полученную здесь информацию на свой страх и риск. Если не указано иное вся информация на этом сайте распространяется по <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.ru">лицензии Creative Commons «Attribution» («Атрибуция») 4.0 Всемирная</a>.<br/>
    <a class="button" href="http://creativecommons.org/licenses/by/4.0/deed.ru"><i class="cc cc-BY"></i></a>

plugins:
    - jekyll-paginate

paginate: 5

highlighter: rouge

kramdown: 
  syntax_highlighter_opts:
    disable : true

future: true

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: Олег Фомичёв
            email: fomich0ff.github.io@gmail.com
            comments: true
            layout: post
            read-more: |
                Читать полностью &raquo;

excerpt_separator: <!--more-->
permalink: pretty

url: https://fomich0ff.github.io

disqus:
    enabled: true
    shortname: fomich0ff-github-io
    nocomments: тишина...

google:
    google-analytics:
        enabled: true
        code: UA-38646029-3

page-navigation:
    enabled: true
    show-pointers: true
    show-labels: false
    show-page-titles: true
    previous:
        label: Назад к
        pointer: |
            &laquo;
    next:
        label: Вперед к
        pointer: |
            &raquo;
pagination:
    prev: Предыдущая страница
    next: Следующая страница
